sudo: required
services:
  - docker

before_install:
  - docker build -t leiw/react-fib-demo -f ./client/Dockerfile.dev ./client

script:
  - docker run leiw/react-fib-demo npm test -- --coverage

after_success:
  - docker build -t leiw/multi-demo-client ./client
  - docker build -t leiw/multi-demo-nginx ./nginx
  - docker build -t leiw/multi-demo-server ./server
  - docker build -t leiw/multi-demo-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push leiw/multi-demo-client
  - docker push leiw/multi-demo-nginx
  - docker push leiw/multi-demo-server
  - docker push leiw/multi-demo-worker